name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  buf-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.15.1
      - uses: bufbuild/buf-lint-action@v1

  buf-breaking:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.15.1
      # The 'main' branch of the GitHub repository that defines the module.
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "${{ github.server_url }}/${{ github.repository }}.git#branch=main"

  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: xt0rted/markdownlint-problem-matcher@v2
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"

  notify:
    runs-on: ubuntu-latest
    if: ${{always()}} && ${{failure()}} && ${{ github.event_name }} == 'push'
    needs:
      - buf-lint
      - buf-breaking
      - markdown-lint
    steps:
      - name: Notify Discord on failure
        uses: sarisia/actions-status-discord@v1
        with:
          username: "Github Actions"
          status: Failure
          nodetail: true
          title: "Workflow: ${{ github.workflow }}"
          url: ${{ github.repositoryUrl }}/actions/runs/${{ github.run_id }}
          description: |
            [@${{ github.actor }}](${{ github.server_url }}/${{ github.actor }}] was the last one to touch ${{ github.repository }}, is all I'm saying...
          avatar_url: "https://media0.giphy.com/media/oe33xf3B50fsc/200.gif"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
